HW 1. Init repo
Rollcorn/formal-lang-course pull request #1
Opened 2024-02-21 17:27 UTC by Rollcorn

2024-03-02 14:53 UTC, KubEF requested changes

2024-03-02 14:53 UTC, KubEF commented on .github/workflows/code_style.yml
> +    branches: [main]
Почему только на main?

2024-03-02 14:53 UTC, KubEF commented on .github/workflows/tests.yml
> +    branches: [main]
То же самое.

2024-03-02 14:53 UTC, KubEF commented on project/graph_helper.py
Просили реализовать функцию, а не класс.

2024-03-02 14:53 UTC, KubEF commented on tests/autotests/test_task1.py
Папка autotests для наших тестов. Кладите, пожалуйста, ваши в отдельную (например, выше).

2024-03-02 14:53 UTC, KubEF commented on tests/autotests/expected/wc_expected.dot
Папка autotests для наших тестов. Кладите, пожалуйста, ваши в отдельную (например, выше).

2024-03-02 14:53 UTC, KubEF commented on tests/autotests/test_task2.py
Не удаляйте наши автотесты.

2024-03-02 14:53 UTC, KubEF commented on tests/autotests/test_task3.py
Не удаляйте наши автотесты.

2024-03-07 10:36 UTC, KubEF commented
Вы поставили pre-commit? У вас code style не проходит.

2024-03-07 10:44 UTC, Rollcorn commented
> Вы поставили pre-commit? У вас code style не проходит.

Исправил. Не сразу до меня дошло что делает black и почему он ругается

2024-03-07 14:18 UTC, KubEF approved these changes

2024-03-10 11:43 UTC, merged